import UIKit

/*
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.

  

 Example 1:

 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:

 Input: s = "", t = "y"
 Output: "y"

 */

func findTheDifference(_ s: String,_ t: String) -> Character {
    var ans: Character = "A"
    var arr = Array(t)
    for item in s {
        if let index = arr.firstIndex(of: item) {
            arr.remove(at: index)
        }
    }
   ans = arr[0]
    return ans
}

findTheDifference1("abcd", "abcde")
//findTheDifference("", "t")

// удаляет все элементы из второй строки, если добавлена такая же буква как в первой строке, удалит ее  тоже
func findTheDifference1(_ s: String, _ t: String) -> Character {
    var t = t
    let charSet: Set<Character> = Set(s)
    t.removeAll(where: charSet.contains)
    
    return Character(t)
}
